### ISSUE TITLE
EDICT2 Incomplete

### ISSUE THREAD

**Issue by PSeitz** [makigumo/wadoku-edict#1]
Some words are missing in the edict2 file like 書く.
The edict contains the entry.

http://www.wadoku.de/wiki/display/WAD/Downloads+und+Links

**Comment by makigumo** [comment]
Are you sure? It seems to be present.

``` sh
$ grep ^書く wadokudict2 
書く種がない [かくたねがない] /nichts haben, über das man schreiben kann/
書く;かく;描く;画く [かく] /schreiben/verfassen/beschreiben/darstellen/schildern/malen/
```

How are you using the file? Maybe there is a different problem causing the words not to be found.

It would be nice if there were a parser to check each line for correctness.

**Comment by PSeitz** [comment]
Sorry, I was using a wrong regex to check. The file is correct.
I tought this was the source, that german entries for 書く were missing in JMDict. But the actual problem is that this entry is mixed with related but different words 描く 画く, so this is harder to match.
